### ISSUE TITLE
[HANDSHAKE] Reporting

### ISSUE THREAD

**Issue by joehand** [datproject/organization#3]
Reporting on our grant from Handshake.

**Comment by RangerMauve** [comment]
- Updated [dat-js](https://github.com/datproject/dat-js#readme) to have faster WebRTC and support for reaching out to the rest of the dat network through a Websocket gateway. Worked off what @karissa had
- Created an [example app](https://github.com/RangerMauve/dat-js-example/) showcasing loading dat content on the web with dat-js
- Updated [browser documentation](https://docs.datproject.org/docs/browser-intro) in docs repo
- Created and published [Datmobile](https://github.com/RangerMauve/datmobile) for viewing Dat Archives on Android. (Ongoing)
- Created [random-access-rn-file](https://github.com/RangerMauve/random-access-rn-file) so that we can persist data in Datmobile. Thanks to @lachenmayer for setting up the test repo

**Comment by RangerMauve** [comment]
@joehand @okdistribute Can this be closed?

**Comment by okdistribute** [comment]
Also handshake supported all of my work that was documented here https://github.com/datproject/planning/issues/11

Thanks handshake!
